# Generated by Django 4.1.4 on 2023-01-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_exopense_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exopense',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
