# Generated by Django 4.1.4 on 2023-01-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_exopense_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exopense',
            options={'verbose_name': 'text'},
        ),
    ]
