# Generated by Django 4.1.4 on 2023-01-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_exopense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exopense',
            options={},
        ),
    ]
